---

# Configurar Load Balancer
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: lb-layer, tags: [lbs, haproxy]}

# Configurar App Servers
- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: app-layer, tags: [apps, tomcat]}

# Configurar DB Servers
- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
#    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [appdbs, postgres]}
